{{- if and .Values.upgrade.username .Values.upgrade.password .Values.upgrade.registry -}}
apiVersion: v1
kind: Secret
metadata:
  name: agent-upgrade-secret
  namespace: {{ .Release.Namespace | quote }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ (include "kubernetes-agent.createHelmRegistryConfig" .) }}
{{- end  -}}