{{- if (include "kubernetes-agent.scriptPodProxies" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: scripts-proxies
  namespace: {{ .Release.Namespace | quote }}
data:
    {{- with .Values.scriptPods.proxies.http_proxy }}
    http_proxy: {{ . | b64enc | quote }}
    HTTP_PROXY: {{ . | b64enc | quote }}
    {{- end }}
    {{- with .Values.scriptPods.proxies.https_proxy }}
    https_proxy: {{ . | b64enc | quote }}
    HTTPS_PROXY: {{ . | b64enc | quote }}
    {{- end }}
    {{- with .Values.scriptPods.proxies.no_proxy }}
    no_proxy: {{ . | b64enc | quote }}
    NO_PROXY: {{ . | b64enc | quote }}
    {{- end }}
{{- end }}