{{- if (include "kubernetes-agent.scriptPodProxies" .) }}

{{/* HTTP PROXY */}}
{{ $httpProxy := "" }}
{{- if .Values.scriptPods.proxies.http_proxy.host }}
{{- if and .Values.scriptPods.proxies.http_proxy.username .Values.scriptPods.proxies.http_proxy.password }}
{{ $httpProxy = printf "http://%s:%s@%s:%d" .Values.scriptPods.proxies.http_proxy.username .Values.scriptPods.proxies.http_proxy.password .Values.scriptPods.proxies.http_proxy.host (.Values.scriptPods.proxies.http_proxy.port | int)  }}
{{- else }}
{{ $httpProxy = printf "http://%s:%d" .Values.scriptPods.proxies.http_proxy.host (.Values.scriptPods.proxies.http_proxy.port | int) }}
{{- end }}
{{- end }}

{{/* HTTPS PROXY */}}
{{ $httpsProxy := "" }}
{{- if .Values.scriptPods.proxies.https_proxy.host }}
{{- if and .Values.scriptPods.proxies.https_proxy.username .Values.scriptPods.proxies.https_proxy.password }}
{{ $httpsProxy = printf "https://%s:%s@%s:%d" .Values.scriptPods.proxies.https_proxy.username .Values.scriptPods.proxies.https_proxy.password .Values.scriptPods.proxies.https_proxy.host (.Values.scriptPods.proxies.https_proxy.port | int)  }}
{{- else }}
{{ $httpsProxy = printf "https://%s:%d" .Values.scriptPods.proxies.https_proxy.host (.Values.scriptPods.proxies.https_proxy.port | int) }}
{{- end }}
{{- end }}


{{/* NO PROXY */}}
{{ $noProxy := "" }}
{{ if .Values.scriptPods.proxies.no_proxy.hosts }}
{{ $noProxy = join "," .Values.scriptPods.proxies.no_proxy.hosts }}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: scripts-proxies
  namespace: {{ .Release.Namespace | quote }}
data:
    {{- if $httpProxy }}
    http_proxy: {{ $httpProxy | b64enc | quote }}
    HTTP_PROXY: {{ $httpProxy | b64enc | quote }}
    {{- end }}
    {{- if $httpsProxy }}
    https_proxy: {{ $httpsProxy | b64enc | quote }}
    HTTPS_PROXY: {{ $httpsProxy | b64enc | quote }}
    {{- end }}
    {{- if $noProxy }}
    no_proxy: {{ $noProxy | b64enc | quote }}
    NO_PROXY: {{ $noProxy | b64enc | quote }}
    {{- end }}
{{- end }}