{{- if (include "kubernetes-agent.useCustomPvc" .) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "kubernetes-agent.pvcName" . }}
  labels:
    {{- include "kubernetes-agent.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  {{- with .Values.persistence.storageClassName }}
  storageClassName: {{ . | quote }}
  {{- end }}  
  {{- with .Values.persistence.volumeName }}
  volumeName: {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size}}
{{- end }} 